### ISSUE TITLE
Initialization of the transition path validation

### ISSUE THREAD

**Issue by jmirabel** [humanoid-path-planner/hpp-manipulation#32]
When the path validation is changed after the graph was created, there is no warning that the graph is not up to date. This might be a desired behavior if the user wants this.

Roadmap to change this:
- add method `GraphComponent::setDirty` to declare an component as dirty (i.e. `isInit_ = false`)
- call this method in `Problem::setPathValidationFactory`
- in `GraphComponent::throwIfNotInitialized`, replace `if (~isInit_)` by
`if (!isInit_ || (graph_ && !graph_.lock()->isInit_) )`

**Comment by rlefevre1** [comment]
It is done.

**Comment by jmirabel** [comment]
#33

**Comment by jmirabel** [comment]
Thanks.
