### ISSUE TITLE
Implementation of LevelSetEdge

### ISSUE THREAD

**Issue by florent-lamiraux** [humanoid-path-planner/hpp-manipulation#79]
I have reworked classes Edge and derived classes (see https://github.com/florent-lamiraux/hpp-manipulation/tree/refactor).

I have written documentation of class LevelSetEdge, trying to stick to ICRA 2017 [paper](https://hal.archives-ouvertes.fr/hal-01358767).

The result is at the end of this message.

@jmirabel : I do not understand the meaning of the condition constraints. They are used only in methods

- populateTooltip, and
- buildHistogram.

![level-set-edge-1](https://user-images.githubusercontent.com/436546/77882098-9296ba80-7260-11ea-825e-a6aeb8ace5f1.png)
![level-set-edge-2](https://user-images.githubusercontent.com/436546/77882123-a04c4000-7260-11ea-8854-a11dc865a16d.png)

**Comment by jmirabel** [comment]
I close this following a oral answer to @florent-lamiraux . The usage of the condition constraint should appear in the doc.
